### ISSUE TITLE
screen shot

### ISSUE THREAD

**Issue by MahdiPishguy** [flipboxstudio/sosoito#4]
is any screen shot for this library?

**Comment by suhafer** [comment]
currently not provide it but here is the screen shot for using this library.

![screenshot_2017-05-24-12-14-53-14](https://cloud.githubusercontent.com/assets/11558708/26387901/6bcd5b80-407b-11e7-9494-0a2a5f13ae17.png)
![screenshot_2017-05-24-12-14-48-11](https://cloud.githubusercontent.com/assets/11558708/26387900/6bcc75c6-407b-11e7-9840-58c421a262d2.png)

**Comment by aqidd** [comment]
@MahdiPishguy you can see the sample implementation and/or screenshots  of this library here https://github.com/flipboxstudio/mvvm-starter
